name: Compile Sketch(1.1.1)

on:
  - workflow_dispatch

jobs:
  compile-sketch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install adafruit-nrfutil
        run: |
          pip3 install adafruit-nrfutil

      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          platforms: |
            - name: Seeeduino:nrf52
              version: 1.1.1
              source-url: https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json
          fqbn: Seeeduino:nrf52:xiaonRF52840
          sketch-paths: |
            - ./examples/
          libraries: |
            - source-url: https://github.com/adafruit/SdFat.git
            - source-url: https://github.com/adafruit/Adafruit_NeoPixel.git
            - source-url: https://github.com/adafruit/Adafruit_Seesaw.git
            - source-url: https://github.com/adafruit/Adafruit_CircuitPlayground.git
            - source-url: https://github.com/FortySevenEffects/arduino_midi_library.git
